name: BlockGame
author: daniel
version: 1.0
main: me.daniel.BlockGame.BlockGamePlugin
description: very fun game
api-version: 1.13
commands:
   startgame:
      description: starts game
      usage: 'Usage: /<command> <players> <duration>'
   skip:
      description: skips block
      usage: 'Usage: /<command> <players>'
   endgame:
      description: ends game
      usage: 'Usage: /<command>'
   pause:
      description: pauses game
      usage: 'Usage: /<command>'
   play:
      description: resumes game after pause
      usage: 'Usage: /<command>'